# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bQt3QtdOkFu0dxdwKWbHwJWbB6tgSDzE
"""

score = int(input("輸入成績"))
if score >= 80:
       print("非常好")
if score >= 60:
       print("不錯喔")
if score < 60:
       print("要加油")

score = int(input("輸入成績"))
if score >= 80:
          print("非常好")
else:
         if score >=60 :
                 print("不錯喔")
         else:
                 print("請加油")

score = int(input("輸入成績"))
if score >=80:
          print("非常好")
elif score >= 60:
          print("不錯喔")
else :
          print("請加油")